services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: apape
      POSTGRES_PASSWORD: apape_dev
      POSTGRES_DB: apape
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
